language: php

php:
    - 5.6
    - 7.0
    - hhvm

before_script:
    - composer install --dev --prefer-dist

script:
    - vendor/bin/phpcs src --standard=phpcs.xml --extensions=php
    - vendor/bin/phpspec run

after_script:
    - php vendor/bin/coveralls -v
